<a href="https://colab.research.google.com/github/annefrancine/ML_2022-2023/blob/main/Conversion_variable_qualitative.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dans les modèles ML, nous sommes souvent amenés à convertir les caractéristiques catégoriques, c'est-à-dire textuelles, en sa représentation numérique. Les deux méthodes les plus courantes pour ce faire sont d'utiliser Label Encoder ou OneHot Encoder. Cependant, la plupart des débutants en ML ne sont pas familiers avec l'impact du choix de l'encodage sur leur modèle, la précision du modèle peut changer en grand nombre en utilisant le bon encodage au bon scénario.

* Comprendre le codage des étiquettes et OneHot.

* Exemple pratique avec Python sur l'impact de l'utilisation de Label et de l'encodage à chaud One sur la précision de la prédiction.

## Encodeur d'étiquette (label encoder):
L'encodage d'étiquettes en Python peut être réalisé à l'aide de la bibliothèque Sklearn. Sklearn fournit un outil très efficace pour coder les niveaux des caractéristiques catégorielles en valeurs numériques. LabelEncoderencoder des étiquettes avec une valeur comprise entre 0 et n_classes-1 où n est le nombre d'étiquettes distinctes. Si une étiquette se répète, elle affecte la même valeur que celle attribuée précédemment.

https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html

Considérez l'exemple ci-dessous:

![image1.png]()

Si nous devons transmettre ces données au modèle, nous devons encoder la colonne Country dans sa représentation numérique à l'aide de Label Encoder. Après avoir appliqué Label Encoder, nous obtiendrons un résultat comme indiqué ci-dessous

![image2.png]()

In [ ]:
# charger les packages
import pandas as pd
import numpy as np
from sklearn import preprocessing #label encoder

In [ ]:
#lire le dataset
df = pd.read_csv("https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv")

In [ ]:
# Afficher les 5 lignes
df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [ ]:
df.describe()

       sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
#identifier les valeurs uniques
df['variety'].unique()

array(['Setosa', 'Versicolor', 'Virginica'], dtype=object)

In [ ]:
# l'objet label_encoder sait comment comprendre les étiquettes de mots.
label_encoder = preprocessing.LabelEncoder()

# Encoder les étiquettes dans la colonne 'variété'.
df['variety']= label_encoder.fit_transform(df['variety'])

df['variety'].unique()

array([0, 1, 2])

In [ ]:
df.head()

   sepal.length  sepal.width  petal.length  petal.width  variety
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [ ]:
df

     sepal.length  sepal.width  petal.length  petal.width  variety
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

## Qu'est-ce que l'encodage à chaud (One hot encoder)?

https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html


Dans l'étape du traitement des données dans le machine learning, nous devons souvent préparer nos données de manière spécifique avant de les alimenter dans un modèle de machine learning. L'un des exemples consiste à effectuer un encodage One-Hot sur des données catégorielles.

Un encodage à chaud est un processus de traitement des données appliqué aux données catégorielles, pour les convertir en une représentation vectorielle binaire à utiliser dans les algorithmes d'apprentissage automatique.

![image3.png]()

In [ ]:
# Lire dataset
st = pd.read_csv("https://gist.githubusercontent.com/GaneshSparkz/b5662effbdae8746f7f7d8ed70c42b2d/raw/faf8b1a0d58e251f48a647d3881e7a960c3f0925/50_Startups.csv")

In [ ]:
#afficher 5 lignes
st.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [ ]:
# valeurs uniques
st['State'].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [ ]:
from sklearn.preprocessing import OneHotEncoder #charger onehotencoder

In [ ]:
#lire le dataset
iris = pd.read_csv("https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv")

In [ ]:
# Afficher les 5 lignes
iris.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [ ]:
#https://pandas.pydata.org/docs/reference/api/pandas.get_dummies.html
#Convertir la variable catégorielle en variables fictives/indicateurs.
dummies = pd.get_dummies(iris.variety)
dummies

     Setosa  Versicolor  Virginica
0         1           0          0
1         1           0          0
2         1           0          0
3         1           0          0
4         1           0          0
..      ...         ...        ...
145       0           0          1
146       0           0          1
147       0           0          1
148       0           0          1
149       0           0          1

[150 rows x 3 columns]

In [ ]:
#Concaténer les variables factices nouvellement créées avec les données chargées et les stocker dans merged_data
merged_data = pd.concat([iris,dummies], axis=1)
merged_data.head()

,sepal.length,sepal.width,petal.length,petal.width,variety,Setosa,Versicolor,Virginica
0,5.1,3.5,1.4,0.2,Setosa,1,0,0
1,4.9,3.0,1.4,0.2,Setosa,1,0,0
2,4.7,3.2,1.3,0.2,Setosa,1,0,0
3,4.6,3.1,1.5,0.2,Setosa,1,0,0
4,5.0,3.6,1.4,0.2,Setosa,1,0,0

En résumé :

- Utilisez LabelEncoder pour des variables catégorielles ordinales lorsque l'ordre entre les catégories a un sens.
- Utilisez OneHotEncoder pour des variables catégorielles nominales lorsque l'ordre n'a pas de sens et que vous voulez éviter de fausses relations d'ordre.

N'oubliez pas que dans de nombreux cas, vous pourriez avoir besoin de combiner ces techniques avec d'autres méthodes de prétraitement de données, telles que la normalisation ou la standardisation, en fonction des exigences spécifiques de votre problème et des algorithmes que vous utilisez